// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InvalidTargetMsg 无效目标消息
//                  在代理服务器检测到目标无效后，发送此消息给与之有关的目标
type InvalidTargetMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidTargetMsg) Reset()         { *m = InvalidTargetMsg{} }
func (m *InvalidTargetMsg) String() string { return proto.CompactTextString(m) }
func (*InvalidTargetMsg) ProtoMessage()    {}
func (*InvalidTargetMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *InvalidTargetMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidTargetMsg.Unmarshal(m, b)
}
func (m *InvalidTargetMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidTargetMsg.Marshal(b, m, deterministic)
}
func (m *InvalidTargetMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidTargetMsg.Merge(m, src)
}
func (m *InvalidTargetMsg) XXX_Size() int {
	return xxx_messageInfo_InvalidTargetMsg.Size(m)
}
func (m *InvalidTargetMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidTargetMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidTargetMsg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*InvalidTargetMsg)(nil), "proto.InvalidTargetMsg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 64 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x42, 0x5c, 0x02, 0x9e, 0x79, 0x65,
	0x89, 0x39, 0x99, 0x29, 0x21, 0x89, 0x45, 0xe9, 0xa9, 0x25, 0xbe, 0xc5, 0xe9, 0x49, 0x6c, 0x60,
	0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0xdb, 0x92, 0x2c, 0x2e, 0x00, 0x00, 0x00,
}
