// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientRegMsg struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRegMsg) Reset()         { *m = ClientRegMsg{} }
func (m *ClientRegMsg) String() string { return proto.CompactTextString(m) }
func (*ClientRegMsg) ProtoMessage()    {}
func (*ClientRegMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_d9d6e8815b86232e, []int{0}
}
func (m *ClientRegMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRegMsg.Unmarshal(m, b)
}
func (m *ClientRegMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRegMsg.Marshal(b, m, deterministic)
}
func (dst *ClientRegMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRegMsg.Merge(dst, src)
}
func (m *ClientRegMsg) XXX_Size() int {
	return xxx_messageInfo_ClientRegMsg.Size(m)
}
func (m *ClientRegMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRegMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRegMsg proto.InternalMessageInfo

func (m *ClientRegMsg) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RawMsg struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Raw                  []byte   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawMsg) Reset()         { *m = RawMsg{} }
func (m *RawMsg) String() string { return proto.CompactTextString(m) }
func (*RawMsg) ProtoMessage()    {}
func (*RawMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_d9d6e8815b86232e, []int{1}
}
func (m *RawMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawMsg.Unmarshal(m, b)
}
func (m *RawMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawMsg.Marshal(b, m, deterministic)
}
func (dst *RawMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawMsg.Merge(dst, src)
}
func (m *RawMsg) XXX_Size() int {
	return xxx_messageInfo_RawMsg.Size(m)
}
func (m *RawMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RawMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RawMsg proto.InternalMessageInfo

func (m *RawMsg) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RawMsg) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type ClientFwdMsg struct {
	ServerType           int32    `protobuf:"varint,1,opt,name=serverType,proto3" json:"serverType,omitempty"`
	Msg                  *RawMsg  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientFwdMsg) Reset()         { *m = ClientFwdMsg{} }
func (m *ClientFwdMsg) String() string { return proto.CompactTextString(m) }
func (*ClientFwdMsg) ProtoMessage()    {}
func (*ClientFwdMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_d9d6e8815b86232e, []int{2}
}
func (m *ClientFwdMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientFwdMsg.Unmarshal(m, b)
}
func (m *ClientFwdMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientFwdMsg.Marshal(b, m, deterministic)
}
func (dst *ClientFwdMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientFwdMsg.Merge(dst, src)
}
func (m *ClientFwdMsg) XXX_Size() int {
	return xxx_messageInfo_ClientFwdMsg.Size(m)
}
func (m *ClientFwdMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientFwdMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ClientFwdMsg proto.InternalMessageInfo

func (m *ClientFwdMsg) GetServerType() int32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *ClientFwdMsg) GetMsg() *RawMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type ServerFwdMsg struct {
	ClientID             int32    `protobuf:"varint,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Msg                  *RawMsg  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerFwdMsg) Reset()         { *m = ServerFwdMsg{} }
func (m *ServerFwdMsg) String() string { return proto.CompactTextString(m) }
func (*ServerFwdMsg) ProtoMessage()    {}
func (*ServerFwdMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_d9d6e8815b86232e, []int{3}
}
func (m *ServerFwdMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerFwdMsg.Unmarshal(m, b)
}
func (m *ServerFwdMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerFwdMsg.Marshal(b, m, deterministic)
}
func (dst *ServerFwdMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerFwdMsg.Merge(dst, src)
}
func (m *ServerFwdMsg) XXX_Size() int {
	return xxx_messageInfo_ServerFwdMsg.Size(m)
}
func (m *ServerFwdMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerFwdMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServerFwdMsg proto.InternalMessageInfo

func (m *ServerFwdMsg) GetClientID() int32 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

func (m *ServerFwdMsg) GetMsg() *RawMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientRegMsg)(nil), "agent.ClientRegMsg")
	proto.RegisterType((*RawMsg)(nil), "agent.RawMsg")
	proto.RegisterType((*ClientFwdMsg)(nil), "agent.ClientFwdMsg")
	proto.RegisterType((*ServerFwdMsg)(nil), "agent.ServerFwdMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientClient interface {
	Register(ctx context.Context, in *ClientRegMsg, opts ...grpc.CallOption) (*ClientRegMsg, error)
	Forward(ctx context.Context, opts ...grpc.CallOption) (Client_ForwardClient, error)
}

type clientClient struct {
	cc *grpc.ClientConn
}

func NewClientClient(cc *grpc.ClientConn) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) Register(ctx context.Context, in *ClientRegMsg, opts ...grpc.CallOption) (*ClientRegMsg, error) {
	out := new(ClientRegMsg)
	err := c.cc.Invoke(ctx, "/agent.Client/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Forward(ctx context.Context, opts ...grpc.CallOption) (Client_ForwardClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Client_serviceDesc.Streams[0], "/agent.Client/Forward", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientForwardClient{stream}
	return x, nil
}

type Client_ForwardClient interface {
	Send(*ClientFwdMsg) error
	Recv() (*ClientFwdMsg, error)
	grpc.ClientStream
}

type clientForwardClient struct {
	grpc.ClientStream
}

func (x *clientForwardClient) Send(m *ClientFwdMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientForwardClient) Recv() (*ClientFwdMsg, error) {
	m := new(ClientFwdMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientServer is the server API for Client service.
type ClientServer interface {
	Register(context.Context, *ClientRegMsg) (*ClientRegMsg, error)
	Forward(Client_ForwardServer) error
}

func RegisterClientServer(s *grpc.Server, srv ClientServer) {
	s.RegisterService(&_Client_serviceDesc, srv)
}

func _Client_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRegMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Client/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Register(ctx, req.(*ClientRegMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServer).Forward(&clientForwardServer{stream})
}

type Client_ForwardServer interface {
	Send(*ClientFwdMsg) error
	Recv() (*ClientFwdMsg, error)
	grpc.ServerStream
}

type clientForwardServer struct {
	grpc.ServerStream
}

func (x *clientForwardServer) Send(m *ClientFwdMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientForwardServer) Recv() (*ClientFwdMsg, error) {
	m := new(ClientFwdMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Client_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Client",
	HandlerType: (*ClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Client_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Forward",
			Handler:       _Client_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	Forward(ctx context.Context, opts ...grpc.CallOption) (Server_ForwardClient, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Forward(ctx context.Context, opts ...grpc.CallOption) (Server_ForwardClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Server_serviceDesc.Streams[0], "/agent.Server/Forward", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverForwardClient{stream}
	return x, nil
}

type Server_ForwardClient interface {
	Send(*ServerFwdMsg) error
	Recv() (*ServerFwdMsg, error)
	grpc.ClientStream
}

type serverForwardClient struct {
	grpc.ClientStream
}

func (x *serverForwardClient) Send(m *ServerFwdMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serverForwardClient) Recv() (*ServerFwdMsg, error) {
	m := new(ServerFwdMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	Forward(Server_ForwardServer) error
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServerServer).Forward(&serverForwardServer{stream})
}

type Server_ForwardServer interface {
	Send(*ServerFwdMsg) error
	Recv() (*ServerFwdMsg, error)
	grpc.ServerStream
}

type serverForwardServer struct {
	grpc.ServerStream
}

func (x *serverForwardServer) Send(m *ServerFwdMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serverForwardServer) Recv() (*ServerFwdMsg, error) {
	m := new(ServerFwdMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Server",
	HandlerType: (*ServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Forward",
			Handler:       _Server_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_agent_d9d6e8815b86232e) }

var fileDescriptor_agent_d9d6e8815b86232e = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x37, 0xae, 0xad, 0xeb, 0x6c, 0x05, 0x19, 0x3d, 0x2c, 0x3d, 0xe8, 0x12, 0x3c, 0xf4,
	0x54, 0xa4, 0x82, 0xe0, 0x79, 0x65, 0x41, 0x44, 0x84, 0xe8, 0x0b, 0x54, 0x77, 0x08, 0x8b, 0xda,
	0x94, 0x24, 0x18, 0xc4, 0x97, 0x97, 0x24, 0x55, 0x8b, 0x04, 0xbc, 0xcd, 0xfc, 0x33, 0xf3, 0xcd,
	0x3f, 0x09, 0xcc, 0x5b, 0x49, 0x9d, 0xad, 0x7b, 0xad, 0xac, 0xc2, 0x2c, 0x24, 0xfc, 0x0c, 0x8a,
	0xd5, 0xeb, 0x96, 0x3a, 0x2b, 0x48, 0xde, 0x19, 0x89, 0xc7, 0x90, 0x59, 0xf5, 0x42, 0xdd, 0x82,
	0x2d, 0x59, 0xb5, 0x2f, 0x62, 0xc2, 0x6b, 0xc8, 0x45, 0xeb, 0x7c, 0x1d, 0x61, 0xd7, 0x7e, 0xf4,
	0x14, 0xca, 0x99, 0x08, 0x31, 0x1e, 0xc2, 0x54, 0xb7, 0x6e, 0xb1, 0xb3, 0x64, 0x55, 0x21, 0x7c,
	0xc8, 0xef, 0xbf, 0xa9, 0x6b, 0xb7, 0xf1, 0x53, 0x27, 0x00, 0x86, 0xf4, 0x3b, 0xe9, 0xc7, 0xdf,
	0xd9, 0x91, 0x82, 0xa7, 0x30, 0x7d, 0x33, 0x32, 0x10, 0xe6, 0xcd, 0x41, 0x1d, 0x7d, 0xc6, 0x8d,
	0xc2, 0x57, 0xf8, 0x2d, 0x14, 0x0f, 0xa1, 0x7d, 0x00, 0x96, 0x30, 0x7b, 0x0e, 0x0b, 0x6e, 0xae,
	0x07, 0xdc, 0x4f, 0xfe, 0x2f, 0xac, 0xf9, 0x84, 0x3c, 0xba, 0xc3, 0x4b, 0x98, 0x09, 0x92, 0x5b,
	0x63, 0x49, 0xe3, 0xd1, 0xd0, 0x39, 0x7e, 0x8e, 0x32, 0x25, 0xf2, 0x09, 0x5e, 0xc1, 0xde, 0x5a,
	0x69, 0xd7, 0xea, 0xcd, 0x9f, 0xb1, 0x68, 0xaf, 0x4c, 0x89, 0x7c, 0x52, 0xb1, 0x73, 0xd6, 0xac,
	0x20, 0x8f, 0x97, 0xa4, 0x20, 0xe3, 0x1b, 0xcb, 0x94, 0x18, 0x21, 0x4f, 0x79, 0xf8, 0xc3, 0x8b,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x66, 0xa5, 0xd6, 0xd2, 0x01, 0x00, 0x00,
}
