// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientLogoutMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientLogoutMsg) Reset()         { *m = ClientLogoutMsg{} }
func (m *ClientLogoutMsg) String() string { return proto.CompactTextString(m) }
func (*ClientLogoutMsg) ProtoMessage()    {}
func (*ClientLogoutMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e20842e418ee7a99, []int{0}
}
func (m *ClientLogoutMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientLogoutMsg.Unmarshal(m, b)
}
func (m *ClientLogoutMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientLogoutMsg.Marshal(b, m, deterministic)
}
func (dst *ClientLogoutMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientLogoutMsg.Merge(dst, src)
}
func (m *ClientLogoutMsg) XXX_Size() int {
	return xxx_messageInfo_ClientLogoutMsg.Size(m)
}
func (m *ClientLogoutMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientLogoutMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ClientLogoutMsg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientLogoutMsg)(nil), "agent.ClientLogoutMsg")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_e20842e418ee7a99) }

var fileDescriptor_message_e20842e418ee7a99 = []byte{
	// 70 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x4c, 0x4f, 0xcd, 0x2b,
	0x51, 0x12, 0xe4, 0xe2, 0x77, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xf1, 0xc9, 0x4f, 0xcf, 0x2f, 0x2d,
	0xf1, 0x2d, 0x4e, 0x4f, 0x62, 0x03, 0x2b, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x7f,
	0x2b, 0x6e, 0x31, 0x00, 0x00, 0x00,
}
