// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InvalidTargetMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidTargetMsg) Reset()         { *m = InvalidTargetMsg{} }
func (m *InvalidTargetMsg) String() string { return proto.CompactTextString(m) }
func (*InvalidTargetMsg) ProtoMessage()    {}
func (*InvalidTargetMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b9ac102e6407d358, []int{0}
}
func (m *InvalidTargetMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidTargetMsg.Unmarshal(m, b)
}
func (m *InvalidTargetMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidTargetMsg.Marshal(b, m, deterministic)
}
func (dst *InvalidTargetMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidTargetMsg.Merge(dst, src)
}
func (m *InvalidTargetMsg) XXX_Size() int {
	return xxx_messageInfo_InvalidTargetMsg.Size(m)
}
func (m *InvalidTargetMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidTargetMsg.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidTargetMsg proto.InternalMessageInfo

func init() {
	proto.RegisterType((*InvalidTargetMsg)(nil), "agent.InvalidTargetMsg")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_b9ac102e6407d358) }

var fileDescriptor_message_b9ac102e6407d358 = []byte{
	// 71 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x4c, 0x4f, 0xcd, 0x2b,
	0x51, 0x12, 0xe2, 0x12, 0xf0, 0xcc, 0x2b, 0x4b, 0xcc, 0xc9, 0x4c, 0x09, 0x49, 0x2c, 0x4a, 0x4f,
	0x2d, 0xf1, 0x2d, 0x4e, 0x4f, 0x62, 0x03, 0xab, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xaa, 0xa2, 0xd5, 0x32, 0x00, 0x00, 0x00,
}
